# Generated by Django 4.0.5 on 2022-06-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
