# Generated by Django 4.0.5 on 2022-06-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0002_project_description_project_keywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
    ]
