# Generated by Django 4.0.5 on 2022-06-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0004_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='logo_image_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portefolio.image'),
        ),
    ]
