# Generated by Django 4.0.5 on 2022-06-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0005_image_project_logo_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
