# Generated by Django 4.0.5 on 2022-06-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0006_alter_image_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='logo_image_id',
        ),
        migrations.AddField(
            model_name='project',
            name='logo_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portefolio.image'),
        ),
    ]
