# Generated by Django 4.0.5 on 2022-06-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0010_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filename',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=0, upload_to='files'),
            preserve_default=False,
        ),
    ]
